/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuctionContract } from "./AuctionContract";
export type { BasicDutchAuction } from "./BasicDutchAuction";
